# Syntax: https://blue-build.org/reference/recipe/
# yaml-language-server: $schema=https://raw.githubusercontent.com/blue-build/cli/main/pkg/recipe-schema.json

name: blueland
description: Custom Bluefin with Hyprland configuration alongside GNOME
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 43

modules:
  # Install comprehensive Hyprland ecosystem
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
    install:
      # Core Hyprland
      - hyprland
      - hyprland-devel
      - hyprpaper
      - hyprlock
      - hypridle
      - hyprpicker
      - hyprcursor
      #- hyprland-qtutils  # deprecated
      
      # Wayland essentials
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      #- xwayland
      - qt5-qtwayland
      - qt6-qtwayland
      
      # Terminal & Shell
      - kitty
      #- foot
      - zsh
      - fish
      - fastfetch
      
      # Application Launchers & Menus
      - rofi-wayland
      - wofi
      - fuzzel
      
      # Notifications
      - dunst
      - mako
      - libnotify
      - swaync
      
      # Status Bar
      - waybar
      
      # Wallpaper Management
      - swww
      - swaybg
      - mpvpaper
      #- wallust
      
      # Screen Locking & Idle
      #- swaylock  #removed because swaylock-effects is more feature-rich fork
      - swaylock-effects
      - swayidle
      
      # Screenshot & Screen Recording
      - grim
      - slurp
      - swappy
      - wf-recorder
      #- wl-screenrec
      
      # Color & Theme Tools
      #- pywal
      #- python3-pywal
      
      # File Managers
      #- nautilus
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - tumbler
      - ffmpegthumbnailer
      
      # System Utilities
      #- polkit-gnome
      #- gnome-keyring
      - brightnessctl
      - light
      - ddcutil
      - wlr-randr
      - wlsunset
      - gammastep
      - emacs
      
      
      # Audio
      - pavucontrol
      - pamixer
      - playerctl
      #- wireplumber
      #- pipewire
      #- easyeffects
      
      # Network
      - network-manager-applet
      - blueman
      
      # System Monitoring
      - btop
      - htop
      - nvtop
      - cava
      
      # Clipboard Manager
      - cliphist
      - wl-clipboard
      
      # Logout Menu
      - wlogout
      
      # Image Viewers
      - imv
      - swayimg
      - viewnior
      
      # Media Player
      #- mpv
      - vlc
      
      # Archive Tools
      - file-roller
      #- p7zip  #already included in bluefin, created dependency conflict, not nescessary
      - unzip
      - unrar
      

      # GTK & Qt Theming
      - nwg-look
      - qt5ct
      - qt6ct
      - kvantum
      - ImageMagick
      #- bibata-cursor-themes
      
      # Python dependencies for JaKooLit scripts
      - python3-pip
      - python3-pillow
      - python3-requests
      - python3-pyquery
      
      # Additional Utilities
      - jq
      - wget
      - curl
      - rsync
      - ripgrep
      - fd-find
      - fzf
      #- eza
      - bat
      - yad
      - wtype
      - ydotool
      - nm-connection-editor
      - emacs
      - kde-connect 
      
      # Display Manager (better for Hyprland than GDM)
      #- sddm
      #- sddm-breeze
      #- sddm-kcm
      #- qt5-qtgraphicaleffects
      #- qt5-qtquickcontrols
      #- qt5-qtquickcontrols2
      #- qt5-qtsvg
      #- lightdm #not wayland native afaik
      #- lightdm-slick-greeter  
      - greetd
      - greetd-tuigreet

    #remove:
      #- gdm
      #- helvum
      #- 2
      #- rygel-preferences
      #- calf -seems to be dependency of some other program I installed above
      #- easyeffects
      #- foot

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode
        - Hack
        - SourceCodePro
        - NerdFontsSymbolsOnly
        - Meslo
        - VictorMono
        - FantasqueSansMono
      google-fonts:
        - Roboto
        - Open Sans
        - Inter


  # Set up systemd services
  - type: systemd
    system:
      enabled:
        - gdm.service
        - bluetooth.service  
      disabled:
        - sddm.service

  # Add custom scripts
  - type: script
    snippets:
      - |
        # Create Hyprland session file for GDM
        mkdir -p /usr/share/wayland-sessions
        cat > /usr/share/wayland-sessions/hyprland.desktop << 'EOF'
        [Desktop Entry]
        Name=Hyprland
        Comment=An intelligent dynamic tiling Wayland compositor
        Exec=Hyprland
        Type=Application
        DesktopNames=Hyprland
        EOF
        chmod 644 /usr/share/wayland-sessions/hyprland.desktop